# Common
rpc.transport=netty
rpc.serializer=kryo
rpc.loadbalancer=random

# Registry
rpc.registry.type=zookeeper
rpc.registry.address=8.134.204.101:2181
rpc.registry.timeout=5000

# Provider
rpc.server.host=127.0.0.1
rpc.server.port=8080
rpc.server.bossThreads=1
rpc.server.workerThreads=4
rpc.server.shutdownTimeout=10
rpc.server.readerIdleTime=30000
rpc.server.writerIdleTime=0
rpc.server.allIdleTime=0

# Consumer
rpc.client.connectTimeout=5000
rpc.client.readTimeout=10000
rpc.client.heartbeatInterval=30000
rpc.client.writerIdleTime=30000
rpc.client.readerIdleTime=10000
rpc.client.retryTimes=3
rpc.client.reconnect.enabled=true
rpc.client.reconnect.maxRetryTimes=5
rpc.client.reconnect.initialDelaySeconds=2
rpc.client.reconnect.maxDelaySeconds=60
rpc.client.reconnect.jitter.enabled=true
rpc.client.reconnect.jitter.minSeconds=0
rpc.client.reconnect.jitter.maxSeconds=1
rpc.client.enableDegradation=false
rpc.client.degradationFailureThreshold=10
